### ISSUE TITLE
Add a github workflow w/multiple emacs version support.

### ISSUE THREAD

**Issue by jasonm23** [sreal/elisp-template#1]
For example:

```
name: Testing {{REPOSITORY}}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - 27.2
          - 28.1
          - snapshot

    steps:    
    - uses: actions/checkout@v3 
    - name: Set up Emacs
      uses: purcell/setup-emacs@v3.0
      with:
        version: ${{ matrix.emacs_version }}

    - name: Emacs init
      run: bin/setup

    - name: examples
      run: bin/test
```
